pipeline {
    agent any
    stages {
        stage('Download Source Code') {
            steps {
                git 'https://github.com/hbchosanna2/finance-solution.git'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }
        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    sh 'mvn sonar:sonar'
                }
            }
        }
        stage('Dockerize') {
            steps {
                sh 'docker build -t <your-docker-registry>/htech-finance-app:latest .'
                sh 'docker push <your-docker-registry>/htech-finance-app:latest'
            }
        }
    }
}
